[project]
name = "primebot-backend"
version = "0.1.0"
description = "PrimeBot Backend"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "babel>=2.18.0",
    "croniter>=6.2.4",
    "cryptography>=50.0.1",
    "discord-py>=2.7.1",
    "django>=5.2,<6.0",
    "django-admin-interface>=0.32.0",
    "django-cors-headers>=4.9.0",
    "django-environ>=0.14.0",
    "django-extensions>=4.1",
    "django-filter>=26.1",
    "django-ical>=1.9.2",
    "django-q2==1.6.2,<1.7.0",
    "django-request>=1.7.1",
    "djangorestframework>=3.18.1",
    "drf-spectacular>=0.30.0",
    "factory-boy>=3.3.3",
    "gunicorn>=26.2.0",
    "hiredis>=3.4.2",
    "multidict==6.9.1",
    "niquests>=3.21.2",
    "psycopg2-binary>=2.9.13",
    "pymongo>=4.18.2",
    "python-telegram-bot==13.15,<14.0",
    "redis>=8.1.0",
    "requests>=2.34.2",
    "Setuptools<81",
]

[tool.black]
line-length = 120
target-version = ['py39']
skip-string-normalization = true
exclude = 'migrations/'

[tool.isort]
line_length = 120
forced_separate = 'tests'
skip = '.venv'
skip_glob = '**/migrations/*.py'
profile = "black"
multi_line_output=3

# ==== Coverage ====
[tool.coverage.run]
omit = ["*/migrations/*", "*/tests/*", "venv/*", "*/wsgi.py", "*/asgi.py", "*.html"]
plugins = ["django_coverage_plugin"]

[dependency-groups]
dev = [
    "django-debug-toolbar>=8.0.0",
    "pre-commit>=4.6.2",
]
