# Generated by Django 3.2.23 on 2024-01-05 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quicklinks_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='is_internal',
            field=models.BooleanField(default=False),
        ),
    ]
