# Generated by Django 3.0.7 on 2020-07-01 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0002_auto_20200701_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_leader',
            field=models.BooleanField(default=False),
        ),
    ]
