# Generated by Django 3.0.8 on 2020-07-07 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0002_auto_20200706_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='telegram_channel_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attr_name', models.CharField(max_length=50)),
                ('attr_value', models.BooleanField()),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.Team')),
            ],
            options={
                'db_table': 'settings',
                'unique_together': {('team', 'attr_name')},
            },
        ),
    ]
