# Generated by Django 3.0.8 on 2020-07-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0003_player_is_leader'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='group_link',
        ),
        migrations.AddField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
