# Generated by Django 3.0.8 on 2020-07-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0004_auto_20200716_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
