# Generated by Django 3.0.8 on 2020-07-04 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0004_auto_20200703_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='summoner_name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
