# Generated by Django 3.0.8 on 2020-07-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0005_team_logo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='team_tag',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
