# Generated by Django 3.0.8 on 2020-07-04 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0006_auto_20200704_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_begin',
            field=models.DateTimeField(null=True),
        ),
    ]
