# Generated by Django 3.0.8 on 2020-07-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0006_auto_20200718_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
