# Generated by Django 3.0.8 on 2020-07-04 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0007_game_game_begin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='latest_suggestion',
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_begin', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.Game')),
            ],
            options={
                'db_table': 'suggestion',
            },
        ),
    ]
