# Generated by Django 3.0.8 on 2020-07-21 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0007_auto_20200718_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='game_result',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.CreateModel(
            name='LiveTicker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_channel_id', models.CharField(max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.Team')),
            ],
            options={
                'unique_together': {('telegram_channel_id', 'sub_team')},
            },
        ),
    ]
