# Generated by Django 3.0.8 on 2020-07-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0008_auto_20200721_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='game_result',
            field=models.CharField(max_length=4, null=True),
        ),
    ]
