# Generated by Django 3.0.8 on 2020-10-04 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0008_auto_20200721_2316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_id', models.CharField(max_length=50)),
                ('content', models.CharField(max_length=3000)),
                ('has_more_content', models.BooleanField(default=False)),
                ('author_name', models.CharField(max_length=50)),
                ('author_id', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.Game')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.Comment')),
            ],
            options={
                'db_table': 'comments',
                'unique_together': {('match', 'comment_id')},
            },
        ),
    ]
