# Generated by Django 3.0.8 on 2021-03-08 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0009_auto_20200919_1747'),
        ('app_prime_league', '0009_comment'),
    ]

    operations = [
    ]
