# Generated by Django 3.0.8 on 2021-03-08 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0010_merge_20210308_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='discord_channel_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_guild_id',
        ),
        migrations.AddField(
            model_name='team',
            name='discord_webhook_id',
            field=models.CharField(max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='team',
            name='discord_webhook_token',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
