# Generated by Django 3.0.8 on 2021-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0012_team_discord_channel_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScoutingWebsite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('base_url', models.CharField(max_length=200)),
                ('separator', models.CharField(max_length=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'scouting_websites',
            },
        ),
    ]
