# Generated by Django 3.0.8 on 2021-05-14 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0012_team_discord_channel_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='discord_role_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
