# Generated by Django 3.0.8 on 2021-09-16 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0014_auto_20210916_2340'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='scouting_website',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='app_prime_league.ScoutingWebsite'),
        ),
    ]
