# Generated by Django 3.0.8 on 2021-09-21 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0015_auto_20210602_2149'),
        ('app_prime_league', '0015_team_scouting_website'),
    ]

    operations = [
    ]
