# Generated by Django 3.0.8 on 2021-09-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0016_merge_20210921_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutingwebsite',
            name='separator',
            field=models.CharField(default=',', max_length=5),
        ),
    ]
