# Generated by Django 3.0.8 on 2021-12-06 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0019_auto_20210923_1551'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Game',
            new_name='Match',
        ),
        migrations.DeleteModel(
            name='TeamWatcher',
        ),
    ]
