# Generated by Django 3.0.8 on 2021-12-07 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0020_auto_20211206_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='match',
            new_name='match',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='game_begin',
            new_name='begin',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='game_closed',
            new_name='closed',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='game_day',
            new_name='match_day',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='match_id',
            new_name='match_id',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='game_result',
            new_name='result',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='game_begin',
            new_name='begin',
        ),
        migrations.RenameField(
            model_name='suggestion',
            old_name='match',
            new_name='match',
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('calibration', 'Kalibrierung'), ('group', 'Pro Division'), ('league', 'Gruppenphase'), ('playoff', 'Playoffs')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterUniqueTogether(
            name='comment',
            unique_together={('match', 'comment_id')},
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('match_id', 'team')},
        ),
        migrations.AlterModelTable(
            name='match',
            table='matches',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='has_more_content',
        ),
    ]
