# Generated by Django 3.0.8 on 2021-12-28 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0021_auto_20211207_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='enemy_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches_as_enemy_team', to='app_prime_league.Team'),
        ),
        migrations.AlterField(
            model_name='match',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches_against', to='app_prime_league.Team'),
        ),
    ]
