# Generated by Django 3.0.8 on 2021-12-28 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0022_auto_20211228_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingsExpiring',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expires', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_expiring', to='app_prime_league.Team')),
            ],
            options={
                'db_table': 'settings_expiring',
            },
        ),
    ]
