# Generated by Django 3.0.8 on 2022-01-17 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0024_changelog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='changelog',
            options={'verbose_name': 'Änderungsprotokoll', 'verbose_name_plural': 'Änderungsprotokolle'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': 'Spielkommentar', 'verbose_name_plural': 'Spielkommentare'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Spiel', 'verbose_name_plural': 'Spiele'},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'verbose_name': 'Spieler', 'verbose_name_plural': 'Spieler'},
        ),
        migrations.AlterModelOptions(
            name='scoutingwebsite',
            options={'verbose_name': 'Scouting-Website', 'verbose_name_plural': 'Scouting-Websites'},
        ),
        migrations.AlterModelOptions(
            name='setting',
            options={'verbose_name': 'Teameinstellung', 'verbose_name_plural': 'Teameinstellungen'},
        ),
        migrations.AlterModelOptions(
            name='settingsexpiring',
            options={'verbose_name': 'Einstellungslink', 'verbose_name_plural': 'Einstellungslinks'},
        ),
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'Zeitvorschlag', 'verbose_name_plural': 'Zeitvorschläge'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Team', 'verbose_name_plural': 'Teams'},
        ),
    ]
