# Generated by Django 3.0.8 on 2022-01-23 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0025_auto_20220117_2033'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_made_latest_suggestion',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
