# Generated by Django 3.0.8 on 2022-01-23 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0026_match_team_made_latest_suggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='match_begin_confirmed',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
