# Generated by Django 3.0.8 on 2022-01-24 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0027_match_match_begin_confirmed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='suggestion',
            options={'verbose_name': 'Terminvorschlag', 'verbose_name_plural': 'Terminvorschläge'},
        ),
    ]
