# Generated by Django 3.0.8 on 2022-02-14 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0028_auto_20220124_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('group', 'Kalibrierung/Pro Div'), ('league', 'Gruppenphase'), ('playoff', 'Playoffs')], max_length=15, null=True),
        ),
    ]
