# Generated by Django 3.0.8 on 2022-02-15 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0029_auto_20220214_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('group', 'Kalibrierung'), ('league', 'Gruppenphase'), ('playoff', 'Playoffs')], max_length=15, null=True),
        ),
    ]
