# Generated by Django 3.0.8 on 2022-02-18 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0030_auto_20220215_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='team_lineup',
            field=models.ManyToManyField(related_name='matches', to='app_prime_league.Player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='enemy_lineup',
            field=models.ManyToManyField(related_name='matches_as_enemy', to='app_prime_league.Player'),
        ),
    ]
