# Generated by Django 3.0.8 on 2022-02-20 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0032_auto_20220219_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scoutingwebsite',
            name='separator',
            field=models.CharField(blank=True, default='', max_length=5),
            preserve_default=False,
        ),
    ]
