# Generated by Django 3.0.8 on 2022-02-20 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0033_auto_20220220_0145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('banned', models.BooleanField()),
                ('banned_until', models.DateField(blank=True, null=True)),
                ('banned_until_patch', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Champion',
                'verbose_name_plural': 'Champions',
                'db_table': 'champions',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='has_side_choice',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
