# Generated by Django 3.0.8 on 2022-06-08 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0035_auto_20220608_1005'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_parent_id', models.IntegerField()),
                ('comment_time', models.DateTimeField()),
                ('content', models.TextField(default='')),
                ('user_id', models.IntegerField()),
                ('comment_edit_user_id', models.IntegerField()),
                ('comment_flag_staff', models.BooleanField()),
                ('comment_flag_official', models.BooleanField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.Match')),
            ],
            options={
                'verbose_name': 'Matchkommentar',
                'verbose_name_plural': 'Matchkommentare',
                'db_table': 'comments',
                'unique_together': {('id', 'match')},
            },
        ),
    ]
