# Generated by Django 3.0.8 on 2022-06-09 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0037_comment_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_edit_user_id',
            field=models.IntegerField(verbose_name='Editiert von'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_flag_official',
            field=models.BooleanField(verbose_name='Official'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_flag_staff',
            field=models.BooleanField(verbose_name='Staff'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_parent_id',
            field=models.IntegerField(verbose_name='Parent ID'),
        ),
    ]
