# Generated by Django 3.0.8 on 2022-06-18 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0038_team_language'),
        ('app_prime_league', '0038_auto_20220609_2000'),
    ]

    operations = [
    ]
