# Generated by Django 3.1.14 on 2022-08-03 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0040_auto_20220701_2112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
