# Generated by Django 3.2.15 on 2023-03-17 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0041_auto_20220803_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='datetime_until_auto_confirmation',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
