# Generated by Django 3.2.23 on 2024-01-11 15:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0043_auto_20231207_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('registration_start', models.DateField()),
                ('registration_end', models.DateField()),
                ('calibration_stage_start', models.DateField(blank=True, null=True)),
                ('calibration_stage_end', models.DateField(blank=True, null=True)),
                ('group_stage_start', models.DateField(blank=True, null=True)),
                ('group_stage_end', models.DateField(blank=True, null=True)),
                ('playoffs_start', models.DateField(blank=True, null=True)),
                ('playoffs_end', models.DateField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
                'db_table': 'splits',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='split',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.split'),
        ),
    ]
