# Generated by Django 3.2.23 on 2024-01-18 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0043_auto_20231207_1502'),
    ]

    operations = [
        migrations.CreateModel(
            name='Split',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('registration_start', models.DateField(help_text='Date when registration starts')),
                ('registration_end', models.DateField(help_text='Date when registration ends')),
                ('calibration_stage_start', models.DateField(blank=True, help_text='Date when calibration stage starts, usually the saturday before the registration ends')),
                ('calibration_stage_end', models.DateField(blank=True, help_text='Date when calibration stage ends, usually the sunday before the registration ends')),
                ('group_stage_start', models.DateField(blank=True, help_text='Date when group stage starts, usually the thursday after the registration ends')),
                ('group_stage_start_monday', models.DateField(blank=True, help_text='Date when group stage starts, usually the next monday after the group stage starts')),
                ('group_stage_end', models.DateField(blank=True, help_text='Date when group stage ends, usually 11 weeks (81 days)')),
                ('playoffs_start', models.DateField(blank=True, help_text='Date when playoffs start, usually the monday after group stage ends')),
                ('playoffs_end', models.DateField(blank=True, help_text='Date when playoffs end, usually 1 week after playoffs start')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Split',
                'verbose_name_plural': 'Splits',
                'db_table': 'splits',
            },
        ),
        migrations.AddField(
            model_name='match',
            name='split',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.split'),
        ),
        migrations.AddField(
            model_name='team',
            name='split',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_prime_league.split'),
        ),
    ]
