# Generated by Django 5.1.1 on 2024-10-15 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0044_auto_20240122_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='enemy_lineup',
            field=models.ManyToManyField(blank=True, related_name='matches_as_enemy', to='app_prime_league.player'),
        ),
        migrations.AlterField(
            model_name='match',
            name='has_side_choice',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='result',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='team_lineup',
            field=models.ManyToManyField(blank=True, related_name='matches', to='app_prime_league.player'),
        ),
    ]
