# Generated by Django 5.0.9 on 2025-01-12 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0045_alter_match_enemy_lineup_alter_match_has_side_choice_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='setting',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='setting',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_prime_league.team'),
        ),
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plattform', models.CharField(choices=[('discord', 'Discord'), ('telegram', 'Telegram')], default='discord', max_length=10)),
                ('telegram_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discord_guild_id', models.CharField(blank=True, max_length=50, null=True)),
                ('discord_webhook_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('discord_webhook_token', models.CharField(blank=True, max_length=100, null=True)),
                ('discord_channel_id', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('language', models.CharField(choices=[('de', 'german'), ('en', 'english')], default='de', max_length=2)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scouting_website', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_prime_league.scoutingwebsite')),
            ],
        ),
        migrations.CreateModel(
            name='ChannelTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('discord_role_id', models.CharField(blank=True, max_length=50, null=True)),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_teams', to='app_prime_league.channel')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='channel_teams', to='app_prime_league.team')),
            ],
        ),
        migrations.AddField(
            model_name='channel',
            name='teams',
            field=models.ManyToManyField(related_name='channels', through='app_prime_league.ChannelTeam', to='app_prime_league.team'),
        ),
        migrations.AddField(
            model_name='setting',
            name='channel_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app_prime_league.channelteam'),
        ),
        migrations.AddField(
            model_name='settingsexpiring',
            name='channel_team',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='settings_expiring', to='app_prime_league.channelteam'),
        ),
        migrations.AddConstraint(
            model_name='channelteam',
            constraint=models.UniqueConstraint(fields=('channel', 'team'), name='unique_channel_team'),
        ),
    ]
