# Generated by Django 5.0.9 on 2025-01-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0047_auto_20250112_1324'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='team',
        ),
        migrations.RemoveField(
            model_name='settingsexpiring',
            name='team',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_channel_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_guild_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_role_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_webhook_id',
        ),
        migrations.RemoveField(
            model_name='team',
            name='discord_webhook_token',
        ),
        migrations.RemoveField(
            model_name='team',
            name='language',
        ),
        migrations.RemoveField(
            model_name='team',
            name='scouting_website',
        ),
        migrations.RemoveField(
            model_name='team',
            name='telegram_id',
        ),
        migrations.AlterField(
            model_name='setting',
            name='channel_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='app_prime_league.channelteam'),
        ),
        migrations.AlterField(
            model_name='settingsexpiring',
            name='channel_team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings_expiring', to='app_prime_league.channelteam'),
        ),
        migrations.AddConstraint(
            model_name='setting',
            constraint=models.UniqueConstraint(fields=('channel_team', 'attr_name'), name='unique_team_setting'),
        ),
    ]
