# Generated by Django 5.0.9 on 2025-01-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0048_remove_setting_team_remove_settingsexpiring_team_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channelteam',
            options={'verbose_name': 'Channel-Team Relation', 'verbose_name_plural': 'Channel-Team Relations'},
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='plattform',
            new_name='platform',
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='channelteam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddConstraint(
            model_name='match',
            constraint=models.UniqueConstraint(fields=('match_id', 'team'), name='unique_match_team'),
        ),
    ]
