# Generated by Django 5.0.9 on 2025-01-28 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prime_league', '0049_alter_channelteam_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='name',
            field=models.TextField(blank=True, default=''),
        ),
    ]
